root: true
extends:
  - plugin:@typescript-eslint/recommended
  - next/core-web-vitals
  - prettier
plugins:
  - import
  - unused-imports
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
rules:
  no-console:
    - warn
    - allow:
        - warn
        - error
  "react/jsx-boolean-value": error
  "react/jsx-curly-brace-presence": error
  "react/self-closing-comp":
    - error
    - component: true
      html: true
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/no-unsafe-call": error
  "@typescript-eslint/no-unsafe-member-access": error
  "@typescript-eslint/no-unsafe-return": error
  prefer-template: error
  "unused-imports/no-unused-imports-ts": warn
  "import/order":
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      pathGroups:
        - pattern: "{react,react-dom/**,react-router-dom}"
          group: builtin
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
