services:
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./nginx:/etc/nginx/templates:ro"
    environment:
      - MINIO_PORT=${MINIO_API_PORT}
      - MEDIA_BUCKET_NAME=${S3_MEDIA_BUCKET_NAME}
  mysql:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=demoice
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9090"
    command: server --console-address ":9090" /data
    volumes:
      - minio-volume:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
  opensearch:
    build: ./opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-volume:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_REST_API_PORT}:9200"
      - "${OPENSEARCH_ANALYZER_PORT}:9600"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    ports:
      - "${OPENSEARCH_DASHBOARDS_PORT}:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
volumes:
  mysql-volume:
    name: mysql-volume
  minio-volume:
    name: minio-volume
  opensearch-volume:
    name: opensearch-volume